# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'relay1_cardano_node'
    static_configs:
    - targets: ['127.0.0.1:12798']
      labels:
        alias: 'relay1'
        type: 'cardano-node'
  - job_name: 'relay1_node_exporter'
    static_configs:
    - targets: ['x.x.x.x:9091']
      labels:
        alias: 'relay1'
        type: 'cardano-node'
  - job_name: 'relay2_cardano_node'
    static_configs:
    - targets: ['x.x.x.x:12798']
      labels:
        alias: 'relay2'
        type:  'cardano-node'
  - job_name: 'relay2_node_exporter'
    static_configs:
    - targets: ['x.x.x.x:9091']
      labels:
        alias: 'relay2'
        type: 'cardano-node'
  - job_name: 'core_cardano_node'
    static_configs:
    - targets: ['x.x.x.x:12798']
      labels:
        alias: 'core'
        type:  'cardano-node'
  - job_name: 'core_node_exporter'
    static_configs:
    - targets: ['x.x.x.x:9091']
      labels:
        alias: 'core'
        type: 'cardano-node'


  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['127.0.0.1:9090']
